# Lab space for Go
# A set of docker containers to experiment code
# Github: https://github.com/awesomelewis2007/lab_space
#
# Targets:
# make - run code

# Folder locations
SRC = src
MAIN = main.go

all: run

run:
	go run $(SRC)/$(MAIN)