# Lab space for Go
# A set of docker containers to experiment code
# Github: https://github.com/0x4248/lab_space
#
# Targets:
# make - run code

# Folder locations
SRC = src
MAIN = main.go

all: run

run:
	go run $(SRC)/$(MAIN)

edit:
	nano $(SRC)/$(MAIN)

edit_vi:
	vi $(SRC)/$(MAIN)

edit_vim:
	vim $(SRC)/ .