# lab space for Elixir
# A set of docker containers to experiment code
# Github: https://github.com/0x4248/lab_space


# Folder locations
SRC = src
MAIN = main.exs

all: run

run:
	elixir $(SRC)/$(MAIN)

edit:
	nano $(SRC)/$(MAIN)

edit_vi:
	vi $(SRC)/$(MAIN)

edit_vim:
	vim $(SRC)/ .