# lab space for Elixir
# A set of docker containers to experiment code
# Github: https://github.com/awesomelewis2007/lab_space


# Folder locations
SRC = src
MAIN = main.exs

all: run

run:
	elixir $(SRC)/$(MAIN)